### ISSUE TITLE
File not found when uploading

### ISSUE THREAD

**Issue by tobada** [web-vision/typo3-ter-ameos_filemanager#1]
Hi,

i installed ameos_filemanager extension Version 1.0.1 in Typo3 7.6.10 instance. After running the update script everything seems to work proberly. 

**Only exception is the upload functionality.** When I try to upload a jpg file to any folder, i get following error:

> Oops, an error occurred!
> 
> File /path/to/file.JPG does not exist.
> 
> More information regarding this error might be available [online](https://wiki.typo3.org/Exception/CMS/1314516809).

The hints in the link could not solve my problem. I appreciate any ideas.

Thanks in advance,
tobada

**Comment by DanielSiepmann** [comment]
Hey @tobada,

thanks for using the updated version of the extension and reporting the issue.
The extension might have some bugs as we just updated the parts we have in use right now.

I try to investigate as soon as possible. When do you need the fix?

**Comment by tobada** [comment]
Hi Daniel,

thanks for investigating. I got the upload working now under Typo3 6.2, no hurry here.

**Comment by DanielSiepmann** [comment]
Hey @tobada,

if you already have a working fix, can you provide a Pull Request?

**Comment by DanielSiepmann** [comment]
As we didn't hear anything again I'm closing this issue.
